# Generated by Django 5.2.8 on 2025-11-07 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(
                        help_text="Número de folio de entrada.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("remitente", models.CharField(max_length=255)),
                ("asunto", models.CharField(max_length=255)),
                ("resumen", models.TextField()),
                ("fecha_recepcion", models.DateField(auto_now_add=True)),
                ("archivo_pdf", models.FileField(upload_to="documentos/entradas/")),
                (
                    "documento_salida",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/salidas/"
                    ),
                ),
                ("fecha_archivo", models.DateField(blank=True, null=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        help_text="Persona que se va a notificar o enviar para su atención.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estatus_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_en_estado",
                        to="core.estatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransicionEstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.documento"
                    ),
                ),
                (
                    "estatus_anterior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transiciones_salidas",
                        to="core.estatus",
                    ),
                ),
                (
                    "estatus_nuevo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transiciones_de_entrada",
                        to="core.estatus",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
