# Generated by Django 5.2.8 on 2025-11-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="fecha_salida",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Salida"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="folio_salida",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Folio de Salida"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="documento_salida",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentos/salidas/",
                verbose_name="Archivo de Salida (Respuesta)",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="fecha_archivo",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Archivado"
            ),
        ),
    ]
