# Generated by Django 5.2.8 on 2025-11-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_documento_fecha_salida_documento_folio_salida_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remitente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Remitente"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Remitentes",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="documento",
            name="remitente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.remitente",
                verbose_name="Remitente de Origen",
            ),
        ),
    ]
