# Generated by Django 5.2.8 on 2025-11-11 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remitente_alter_documento_remitente"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="remitente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.remitente",
                verbose_name="Remitente",
            ),
        ),
        migrations.RemoveField(
            model_name="documento",
            name="responsable",
        ),
        migrations.AddField(
            model_name="documento",
            name="responsable",
            field=models.ManyToManyField(
                limit_choices_to={"groups__name": "Responsable"},
                related_name="documentos_asignados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable(s) Asignados",
            ),
        ),
    ]
