# Generated by Django 5.2.8 on 2025-11-11 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_documento_remitente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="responsables_adicionales",
            field=models.ManyToManyField(
                blank=True,
                related_name="documentos_adicionales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsables Adicionales",
            ),
        ),
        migrations.RemoveField(
            model_name="documento",
            name="responsable",
        ),
        migrations.AddField(
            model_name="documento",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documento",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable Principal",
            ),
        ),
    ]
