# Generated by Django 5.2.8 on 2025-11-11 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_documento_responsables_adicionales_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transicionestatus",
            options={
                "verbose_name": "Transición de Estatus",
                "verbose_name_plural": "Transiciones de Estatus",
            },
        ),
        migrations.RenameField(
            model_name="transicionestatus",
            old_name="timestamp",
            new_name="fecha_transicion",
        ),
        migrations.RemoveField(
            model_name="transicionestatus",
            name="estatus_anterior",
        ),
        migrations.RemoveField(
            model_name="transicionestatus",
            name="estatus_nuevo",
        ),
        migrations.RemoveField(
            model_name="transicionestatus",
            name="usuario",
        ),
        migrations.AddField(
            model_name="transicionestatus",
            name="comentario",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentarios del Turno"
            ),
        ),
        migrations.AddField(
            model_name="transicionestatus",
            name="nuevo_estatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.estatus",
                verbose_name="Nuevo Estatus",
            ),
        ),
        migrations.AddField(
            model_name="transicionestatus",
            name="responsable_destino",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_asignados_historial",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable Destino",
            ),
        ),
        migrations.AddField(
            model_name="transicionestatus",
            name="usuario_origen",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transiciones_realizadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario Origen",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="responsable",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documento",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="responsables_adicionales",
            field=models.ManyToManyField(
                blank=True,
                related_name="documentos_adicionales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Otros",
            ),
        ),
        migrations.AlterField(
            model_name="transicionestatus",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.documento",
                verbose_name="Documento Auditado",
            ),
        ),
    ]
