# Generated by Django 5.2.8 on 2025-11-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_transicionestatus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="remitente",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="remitente",
            name="trato",
            field=models.CharField(
                choices=[
                    ("Dip", "Diputado/a"),
                    ("C", "Ciudadano/a"),
                    ("Mtro", "Maestro/a"),
                    ("Dr", "Doctor/a"),
                    ("Ing", "Ingeniero/a"),
                    ("Pdte", "Presidente"),
                    ("Pdta", "Presidenta"),
                ],
                default="C.",
                max_length=10,
            ),
        ),
    ]
