# Generated by Django 5.2.8 on 2025-11-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remitente_area_remitente_trato"),
    ]

    operations = [
        migrations.AddField(
            model_name="remitente",
            name="correo",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
    ]
