# Generated by Django 5.2.8 on 2025-11-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remitente_correo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remitente",
            name="correo",
        ),
    ]
