# Generated by Django 5.2.8 on 2025-11-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_remitente_correo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documento",
            old_name="fecha_recepcion",
            new_name="fecha_captura",
        ),
    ]
