# Generated by Django 5.2.8 on 2025-11-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_fecha_recepcion_documento_fecha_captura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="fecha_captura",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Captura"
            ),
        ),
    ]
