# Generated by Django 5.2.8 on 2025-11-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_documento_fecha_captura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="folio_salida",
        ),
    ]
