# Generated by Django 5.2.8 on 2025-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_documento_folio_salida"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transicionestatus",
            options={"ordering": ["fecha_transicion"]},
        ),
        migrations.AlterField(
            model_name="transicionestatus",
            name="comentario",
            field=models.TextField(blank=True, null=True),
        ),
    ]
