# Generated by Django 5.2.8 on 2025-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_transicionestatus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="folio_salida",
            field=models.CharField(
                blank=True,
                help_text="Número de folio de salida.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Folio de Salida",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="resumen_responsable",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resumen del Responsable"
            ),
        ),
    ]
