# Generated by Django 5.2.8 on 2025-11-18 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_documento_folio_salida_documento_resumen_responsable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="responsables_que_enviaron_resumen",
            field=models.ManyToManyField(
                blank=True,
                related_name="documentos_con_resumen_enviado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsables que enviaron resumen",
            ),
        ),
    ]
