# Generated by Django 5.2.8 on 2025-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_resumenresponsableadicional"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="asunto_salida",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Asunto de Salida"
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="contenido_respuesta",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contenido de la Respuesta"
            ),
        ),
    ]
